name: Build Binaries

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
          
      - name: Install dependencies
        run: |
          go get github.com/getlantern/systray
          go mod tidy
          go mod download

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libayatana-appindicator3-dev

      - name: Build binary for Linux
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/wazuh-tray .

      - name: Upload Linux binary
        uses: actions/upload-artifact@v2
        with:
          name: wazuh-tray-linux-amd64
          path: dist/wazuh-tray

  build-macos:
    runs-on: macos-latest
    needs: build-linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
          
      - name: Install dependencies
        run: |
          go get github.com/getlantern/systray
          go mod tidy
          go mod download

      - name: Build binary for macOS
        run: |
          mkdir -p dist
          CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o dist/wazuh-tray

      - name: Upload macOS binary
        uses: actions/upload-artifact@v2
        with:
          name: wazuh-tray-darwin-amd64
          path: dist/wazuh-tray

  build-windows:
    runs-on: ubuntu-latest
    needs: build-macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
          
      - name: Install dependencies
        run: |
          go get github.com/getlantern/systray
          go mod tidy
          go mod download

      - name: Build binary for Windows
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 go build -o dist/wazuh-tray.exe

      - name: Upload Windows binary
        uses: actions/upload-artifact@v2
        with:
          name: wazuh-tray-windows-amd64
          path: dist/wazuh-tray.exe
