name: Build Binaries for macOS (Silicon ARM64)

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:

env:
  GO_VERSION: 1.22
  APP_NAME: wazuh-agent-status

jobs:
  build-macos:
    name: Build for macOS ARM64
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install MacOS Dependencies
        run: |
          brew install gtk+3

      - name: Build binary for macOS Silicon (ARM64)
        run: |
          GOOS=darwin GOARCH=${{ matrix.arch }} go build -o dist/${{ env.APP_NAME }}-darwin-${{ matrix.arch }}

      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-darwin-${{ matrix.arch }}
          path: ./dist/