name: Build Binaries for Windows (Silicon AMD64)

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:

env:
  GO_VERSION: 1.22
  APP_NAME: wazuh-agent-status

jobs:
  build-windows:
    name: Build for Windows AMD64
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: |
          go mod tidy

      - name: Build binary for Windows
        run: |
          go build -o dist/${{ env.APP_NAME }}-windows-${{ matrix.arch }}.exe

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-windows-${{ matrix.arch }}
          path: ./dist/