name: Wazuh Agent Status - Rust Components CI

on: [pull_request]

jobs:
  cargo-fmt:
    name: Cargo Format Check - ${{ matrix.component.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - { dir: "wazuh-agent-status-rust-server", name: "Server" }
          - { dir: "wazuh-agent-status-rust-client/src-tauri", name: "Client" }
    defaults:
      run:
        working-directory: ./${{ matrix.component.dir }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-env

      - name: Rustfmt Check
        run: cargo fmt --all -- --check

  cargo-clippy:
    name: Cargo Clippy Check - ${{ matrix.component.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - { dir: "wazuh-agent-status-rust-server", name: "Server" }
          - { dir: "wazuh-agent-status-rust-client/src-tauri", name: "Client" }
    defaults:
      run:
        working-directory: ./${{ matrix.component.dir }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-env

      - name: Install Tauri system dependencies (Client only)
        if: matrix.component.name == 'Client'
        uses: ./.github/actions/setup-tauri-deps

      - name: Clippy Check
        run: cargo clippy --workspace --all-targets --all-features

  cargo-nextest:
    name: Cargo Nextest - Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wazuh-agent-status-rust-server
    steps:
      - name: Fetch Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-env

      - name: Install cargo-nextest
        uses: taiki-e/install-action@b550161ef8a7bc4f2a671c0b03a18ac9ccedea1e # v2
        with:
          tool: nextest

      - name: Run Cargo Tests
        run: cargo nextest run --workspace --all-targets --all-features

  cargo-machete:
    name: Cargo Machete Check - ${{ matrix.component.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - { dir: "wazuh-agent-status-rust-server", name: "Server" }
          - { dir: "wazuh-agent-status-rust-client/src-tauri", name: "Client" }
    defaults:
      run:
        working-directory: ./${{ matrix.component.dir }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-env

      - name: Check for unused dependencies
        uses: taiki-e/install-action@b550161ef8a7bc4f2a671c0b03a18ac9ccedea1e # v2
        with:
          tool: cargo-machete

      - name: Cargo Machete
        run: cargo machete --with-metadata
