name: Wazuh Agent Status - Rust Components CI

on: [pull_request]

jobs:
  cargo-fmt:
    name: Cargo Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-env

      - name: Rustfmt Check Server
        run: cargo fmt --all -- --check
        working-directory: ./wazuh-agent-status-rust-server

      - name: Rustfmt Check Client
        run: cargo fmt --all -- --check
        working-directory: ./wazuh-agent-status-rust-client/src-tauri

  cargo-clippy:
    name: Cargo Clippy Check
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-env

      - name: Install Tauri system dependencies
        uses: ./.github/actions/setup-tauri-deps

      - name: Clippy Check Server
        run: cargo clippy --all-targets --all-features
        working-directory: ./wazuh-agent-status-rust-server

      - name: Clippy Check Client
        run: cargo clippy --all-targets --all-features
        working-directory: ./wazuh-agent-status-rust-client/src-tauri

  cargo-nextest:
    name: Cargo Nextest - Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wazuh-agent-status-rust-server
    steps:
      - name: Fetch Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-env

      - name: Install cargo-nextest
        uses: taiki-e/install-action@b550161ef8a7bc4f2a671c0b03a18ac9ccedea1e # v2
        with:
          tool: nextest

      - name: Run Cargo Tests
        run: cargo nextest run --all-targets --all-features

  cargo-machete:
    name: Cargo Machete Check
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Rust Environment
        uses: ./.github/actions/setup-rust-env

      - name: Check for unused dependencies
        uses: taiki-e/install-action@b550161ef8a7bc4f2a671c0b03a18ac9ccedea1e # v2
        with:
          tool: cargo-machete

      - name: Cargo Machete Server
        run: cargo machete --with-metadata
        working-directory: ./wazuh-agent-status-rust-server

      - name: Cargo Machete Client
        run: cargo machete --with-metadata
        working-directory: ./wazuh-agent-status-rust-client/src-tauri
