name: SonarQube

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    uses: ADORSYS-GIS/adorsys-ci-cd-templates/.github/workflows/sonarqube.yml@1566ed0da26bd29f41625655dd7171a5464762fd
    with:
      project-key: wazuh-agent-status
      exclusions: "**/target/**,**/node_modules/**,**/dist/**,**/coverage/**"
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}